baseURL = "https://ndis.lgbt/"
languageCode = "en-us"
title = "NDISdotLGBT"

[params]
  contentTypeName = "posts"

[params.docs]
  darkMode = "true"

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
